package project_alias.forms;

import ua.com.fielden.platform.entity.fetch.IFetchProvider;
import ua.com.fielden.platform.utils.EntityUtils;
import ua.com.fielden.platform.dao.IEntityDao;

/**
 * Companion object for entity {@link FormClass}.
 *
 * @author Peoject-alias team
 *
 */
public interface FormClassCo extends IEntityDao<FormClass> {
    
    static final String DEFAULT_KEY_VALUE = "Autogenerated";
    static final String FORM_CLASS_KEY_NAME = "FormClass NO";
    
    static final IFetchProvider<FormClass> FETCH_PROVIDER = EntityUtils.fetch(FormClass.class)
            .with("person", "status", "date", "formType"); //formType
}
